### ISSUE TITLE
[Feature Request] Quick Stack Categories

### ISSUE THREAD

**Issue by greenconda** [Goldenrevolver/QuickStackStore#11]
I would like to request a feature if its possible, to categorize items like seeds, metals meats, etc so that it stacks items in container having similar items even if that specific item is not in any container

**Comment by Goldenrevolver** [comment]
that sounds exactly like what [Smarter Containers](https://www.nexusmods.com/valheim/mods/332) does. it looks a bit buggy but it has been around for one and a half years, so I'm not gonna compete with their niche

also on a more technical side: keeping quick stacking performance friendly is a pain. the single feature of treating trophies differently than all other features almost doubled the quick stacking time (which is why it's disabled by default). so doing that for multiple more categories (and people would always ask for new ones) does not interest me. smart containers gets around this with a different design of how it works (stacking anywhere and then sorting afterwards)
