### ISSUE TITLE
mod not loading

### ISSUE THREAD

**Issue by marcowesii** [Goldenrevolver/QuickStackStore#21]
win 10, rtx 3070, 5900hx.
Tried bepinex v5.4.20 v5.4.17 v5.4.21 v5.4.22 with both configuration manager and not. Mod seems to be loading correctly from bepinex logs but doesn't graphically load or is present in configuration manager.
Am I doing something wrong?

Thanks for you time.

**Comment by Goldenrevolver** [comment]
thank you for opening an issue. from what you currently said no. you should use quickstackstore with the most updated version of bepinex. I set the mod to ask for version 5.4.2200, but the newest version 5.4.2202 also works. my mod only supports the most updated version of valheim 0.217.25

so my guess is that you are using the mod "trash items" by virtuacode. this mod is a hard incompatibility (because my mod provides identical features), so my mod shuts down when it's installed. please report back if this was the issue

**Comment by Goldenrevolver** [comment]
does the thumbs up mean this was the issue, @marcowesii ?

**Comment by marcowesii** [comment]
I'm trying right now, it was a feedback, sorry for miscommunication.

**Comment by marcowesii** [comment]
Being the [censored] I am, I was using default vanilla bepinex and not the already customized one, so bepinex started not correctly even though it was creating some logs >:( , apart from configuration manager that seemed to work.
Now the mod seems to work wonders, I'm going to test the mod in the weekend.
Thanks for the kind reply and your time! :)
