### ISSUE TITLE
Restocking does not work for meads

### ISSUE THREAD

**Issue by nerolite** [Goldenrevolver/QuickStackStore#26]
The restock functionality does not work for meads.

It works for other items such as food, ammo and wood -given that I have the latter enabled.
However, restocking does not fill up any of my meads* including major healing mead, lingering stamina mead, nor the fire resistance barley wine.

I have experimented with various configuration settings to try to get it to work.

Is this intended behavior?

*items from the fermenter 

P.S. Appreciate the great mod!

**Comment by Goldenrevolver** [comment]
this should and does work on past and the current version, but it's managed by quite a few variables. mead counts as a consumable, so it is affected by RestockOnlyAmmoAndConsumables and RestockStackSizeLimitConsumables. in the default config template it should be allowed to restock them. in my config template (goldens choice), I instead use RestockOnlyFavoritedItems, so my potions have to be favorited to get restocked. please go through the restock settings again to see what is wrong.

and if you are using a mod that adds "custom data" to the potions, like them spoiling or having quality or something, then my mod cannot stack them (because that would destroy the custom data of the other mod)
