### ISSUE TITLE
Single-player only?

### ISSUE THREAD

**Issue by MyrddinE** [Goldenrevolver/QuickStackStore#7]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/435613/219981522-1134a17e-bfa7-478d-8398-548016608f1a.png">
When running locally it's fine, but when I host a server locally many of the mods features disappear. In the screenshot you can see that my item and slot locking are active and working, but the R(estock) and Q(uick dump) buttons are missing.

What am I doing incorrectly?

**Comment by Goldenrevolver** [comment]
you did not enable them in the config

most likely you have section "2 - Quick Stacking and Restocking" setting "AllowAreaStackingInMultiplayerWithoutMUC" disabled. this was changed to be disabled by default because I cannot guarantee that there will never be item loss when multiple people access the same chests with different mods at the same time, when you are not using the mod 'multi user chest' (MUC). this makes it less annoying for server owners because they can control that setting of their users if the mod is also installed on the server (the setting is serversynced)
